    title: Cintia Magalh√£es 
    description: Technical Writer
    theme: just-the-docs

    url: https://github.com/cikasm/docs-website.git

    search_enabled: false
    baseurl: /test-class


    aux_links: # remove if you don't want this link to appear on your pages
   
      
 
